# Site settings
title: IZTech - Desenvolvendo a web
email: izinenda@outlook.com
description: Focados no desenvolvimento da WWW 
url: "http://zinenda.github.io/iztech"
twitter:
    username: Imaz_3g
github: Zinenda
facebook: zinenda.jerk
google: +IvoZinenda
linkedin: zinendajerk

deploy:
- rsync -aze ssh --delete ./ https://github.com/Zinenda/iztech.git

# Build settings
markdown: kramdown

sass:
    sass_dir: assets/_sass
    style: compressed