# Site settings
title: IZTech
email: izinenda@outlook.com
description: Desenvolvendo a web 
#url: "http://zinenda.github.io/iztech"
twitter:
    username: Imaz_3g
github: Zinenda
facebook: zinenda.jerk
google: +IvoZinenda
linkedin: zinendajerk
author: Ivo Zinenda

deploy:
- rsync -aze ssh --delete ./ https://github.com/Zinenda/iztech.git

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
sass:
    sass_dir: assets/_sass
    style: compressed